# -*- coding: utf-8 -*-
"""thyroid-nodule-classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J5l257y4AptIH0KuffjlpSNXxstcqCsd

# Thyroid Nodule Ultrasound Analysis & TI-RADS Classification Using CNN and Transfer Learning Architectures

This project focuses on analyzing thyroid nodule ultrasound images and predicting their **TI-RADS (Thyroid Imaging Reporting and Data System) scores**.

I was personally motivated to work on this project because I have experienced **acute hyperthyroidism**, and my mother currently suffers from **hypothyroidism**. Seeing the impact thyroid disorders can have on everyday life inspired me to explore how deep learning can assist in **early detection and risk stratification** of thyroid nodules.

Thyroid nodules are common, and ultrasound imaging is the primary tool for assessing potential risk.
TI-RADS scoring helps clinicians decide whether a nodule requires a follow-up or further medical and coslty intervention like a biopsy.

Automating TI-RADS classification using deep learning can:
- Standardize readings across different clinicians
- Speed up diagnosis
- Assist radiologists in decision-making

The dataset comes from the Columbia thyroid ultrasound collection and includes:
- 400 patients and their thyroid nodules ultrasound images
- Annotation files (XML) with nodule regions marked via SVG polygons
- Metadata for each image including patient age and sex, composition, echogenicity, margins, calcifications, and TI-RADS score

The main goals of this project are:
1. Parse and organize the dataset (images, XML annotations, metadata)
2. Visualize nodules and their annotations
3. Generate binary masks from SVG points for segmentation
4. Build a **multimodal deep learning model** using:
   - CNN for image features
   - Metadata features for improved prediction
5. Predict **multiclass TI-RADS scores** for nodules
6. Evaluate model performance with accuracy, F1 score, and confusion matrix

#1.0 Import Libraries
"""

import os
import pandas as pd
import numpy as np
import xml.etree.ElementTree as ET # to handle xml data
import json # to convert the scalable vector graphic (svg) points in the xml file
from PIL import Image, ImageOps
import matplotlib.pyplot as plt
import cv2 # used to fill mask
from sklearn.model_selection import train_test_split
from sklearn.utils.class_weight import compute_class_weight
import tensorflow as tf
from tensorflow.keras import layers, models, Input
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.applications import DenseNet121
from sklearn.metrics import classification_report, confusion_matrix
import random

random.seed(42)
np.random.seed(42)
tf.random.set_seed(42)

"""#2.0 Import, Inspect and Clean Data

We'll create a base directory object where the entire files are located then we'll list all files and split them by their file extension and see how many xml and image files we're working with.
"""

base_dir = "/content/thyroid-nodules"

all_files = os.listdir(base_dir)

xml_files = [os.path.join(base_dir, f) for f in all_files if f.lower().endswith(".xml")]
jpeg_files = [os.path.join(base_dir, f) for f in all_files if f.lower().endswith((".jpg", ".jpeg"))]

print(f"Found {len(xml_files)} XML files and {len(jpeg_files)} JPEG files.")

xml_files[0]

"""## 2.1 Check Sample XML File"""

example_xml = xml_files[0]
example_path = os.path.join(base_dir, example_xml)

tree = ET.parse(example_path)
root = tree.getroot()

# print XML as string for 500 strings for readability

xml_str = ET.tostring(root, encoding = 'unicode')
print("Example XML file content:\n")
print(xml_str[:500], "\n...")

"""## 2.2 Prepare Metadata Structures by Creating a Dictionary for the Metadata and the SVG Points"""

metadata_data = {
    "Number": [],
    "Age": [],
    "Sex": [],
    "Composition": [],
    "Echogenicity": [],
    "Margins": [],
    "Calcifications": [],
    "Tirads": [],
    "Reportbacaf": [],
    "Reporteco": [],
}

svg_polygons = {}  # key: "{case_number}_{image_index}" -> list of polygons

invalid_images = set()

for xml_path in xml_files:
    tree = ET.parse(xml_path)
    root = tree.getroot()

    # metadata elements

    def get_text(tag):
        node = root.find(tag)
        return node.text if node is not None else None

    case_number = get_text("number")
    metadata_data["Number"].append(int(case_number) if case_number else None)

    age_text = get_text("age")
    metadata_data["Age"].append(int(age_text) if age_text else None)

    for tag in ["Sex", "Composition", "Echogenicity", "Margins", "Calcifications", "Tirads", "Reportbacaf", "Reporteco"]:
        metadata_data[tag].append(get_text(tag.lower()))

    # mark nodes containing the image number and associated svg points

    for mark in root.findall("mark"):
        image_idx_node = mark.find("image")
        svg_node = mark.find("svg")

        # check if the mark tags are in the xml file, if not skip this xml
        if image_idx_node is None or svg_node is None:
            continue

        image_idx = image_idx_node.text
        svg_text = svg_node.text

        # if there is those mark tags, check if svg_text is empty or missing, if not skip this xml
        if not svg_text or not svg_text.strip():
            continue

        try:
        # try to parse JSON, if error happens then...
          polygons = json.loads(svg_text)
          svg_polygons[f"{case_number}_{image_idx}"] = polygons

        # handle the error
        except json.JSONDecodeError:
          snippet = svg_text[-50:]  # last 50 chars for debugging
          invalid_images.add(f"{case_number}_{image_idx}") # blacklist
          print(f"⚠️ Skipping invalid JSON in case {case_number}, image {image_idx}")
          print(f"Snippet: {snippet}")

"""Since these amount of errors from trying to parse the json strings into python objects is small we will not use these images in our training, validation, and test sets. They'll be stored in the invalid_images blacklist.

##2.3 Create dataframe for metadata
"""

metadata_df = pd.DataFrame(metadata_data)
metadata_df.sort_values(by = "Number", inplace = True)
metadata_df.set_index("Number", inplace = True)

metadata_df.info()

metadata_df.isnull().sum()

metadata_df

metadata_df[metadata_df["Age"].isnull()]

# count what each column contains and what each variable is (doesn't count NaN or None)

for col in metadata_df.columns:
    print(f"\nColumn: {col}")
    print(metadata_df[col].value_counts())

"""We will drop the Age and Sex columns because they contain 86 and 85 null values, respectively. These rows also have missing values in other columns, affecting 21.5% of the dataset. Dropping the rows would remove too much data, so it is preferable to drop the columns instead. We will retain the TI-RADS column, as a missing value would indicate a normal image. The Reportbacaf and Reporteco columns will also be removed.

For the categorical features, we will apply one-hot encoding to Sex, Composition, Echogenicity, Margins (after correcting “ill defined”), and Calcifications (after combining “micro” and “macro” categories).

The target variable for modeling will be TI-RADS.

TI-RADS shows scores of 2, 3, 4a, 4b, 4c and 5 while 92 rows are missing. I'm assuming those rows are having no score meaning because they are benign, a non malignant non canerous thyroid nodule. For this, I'll assign them with 1.

"""

# create a new column for margins where "ill- defined" becomes "ill defined"

metadata_df["Margins_new"] = metadata_df["Margins"].replace({"ill- defined": "ill defined"})

# create a new column for calcifications combining the micros and macros and renaming non to none

metadata_df["Calcifications_new"] = metadata_df["Calcifications"].replace({
    "microcalcification": "microcalcifications",
    "macrocalcification": "macrocalcifications",
    "non": "none"
})

"""Copy metadata_df to new cleaned dataframe with one-hot encoded sex, echogenecity, composition, margins_new, calcifications_new columns"""

metadata_df_clean = metadata_df.copy()
metadata_df_clean = pd.get_dummies(
    metadata_df_clean,
    columns = ["Echogenicity", "Composition", "Margins_new", "Calcifications_new"],
    drop_first = False
)

metadata_df_clean.drop(columns = ["Age", "Sex", "Margins", "Calcifications", "Reportbacaf", "Reporteco"], inplace = True)

metadata_df_clean.info()

metadata_df_clean.isnull().sum()

# fill None in tirads column with 1

metadata_df_clean['Tirads'] = metadata_df_clean['Tirads'].fillna("1")

metadata_df_clean.head(5)

metadata_df_clean.tail(10)

# convert only boolean columns to 1 and 0

# select only the boolean columns (the dummies)
bool_cols = metadata_df_clean.select_dtypes(include="bool").columns

# convert just those columns to integers
metadata_df_clean[bool_cols] = metadata_df_clean[bool_cols].astype(int)

metadata_df_clean.head(5)

print("\nExample SVG key and polygons:")
key = list(svg_polygons.keys())[0]
print("Key:", key)
print("Type:", type(svg_polygons[key]))
print("Full SVG string:\n", svg_polygons[key][:1000])

"""## 2.4 Check and clean images

Next, we'll check the image dimensions. This step is important for a few reasons:

- Consistency for modeling: CNNs need all images to have the same height and width, so verifying dimensions helps ensure everything is ready for resizing or batching.

- SVG coordinate alignment: The SVG points are mapped in pixel coordinates relative to each image. Knowing the exact size is necessary to generate masks correctly to overlay the ultrasound image.

- Catching corrupted or odd files: Sometimes an image might have an unexpected shape, number of channels, or file format, so this step helps spot and fix those issues early.
"""

dimensions = []

for img_path in jpeg_files:
    with Image.open(img_path) as img:
        width, height = img.size
        dimensions.append((img_path, width, height))

# Print a few examples
for i, (path, w, h) in enumerate(dimensions[:5]):
    print(f"{i+1}: {path} -> {w}x{h}")

# Check unique dimensions
unique_sizes = set((w, h) for _, w, h in dimensions)
print("\nUnique image sizes:", unique_sizes)

"""Since ultrasound images have dimensions 560x360, we need them to be squares or 224x224 to work with CNN architectures. We'll resize the images but keep the proportions and add padding around the images to reach the target size."""

# path of images

img_dir = base_dir  # JPEGs are directly under base_dir
TARGET_SIZE = (224, 224)  # CNN input size (width, height)

"""We'll create functions to scale the images and create a black and white mask to bifurcate the thyroid nodules in the images (white being the segment of interest)"""

def scale_points(points, orig_size, target_size):
    """Scale SVG points to match resized image size"""
    orig_w, orig_h = orig_size
    target_w, target_h = target_size
    scale_x = target_w / orig_w
    scale_y = target_h / orig_h
    return [{"x": int(p["x"] * scale_x), "y": int(p["y"] * scale_y)} for p in points]

def scale_points(points, orig_size, target_size):
    """Scale SVG points to match resized image size"""
    orig_w, orig_h = orig_size
    target_w, target_h = target_size

    # Compute scale while keeping aspect ratio
    scale = min(target_w / orig_w, target_h / orig_h)

    # Compute padding added to center the image
    pad_w = (target_w - orig_w * scale) / 2
    pad_h = (target_h - orig_h * scale) / 2

    # Scale and shift points
    scaled = []
    for pt in points:
        x = pt["x"] * scale + pad_w
        y = pt["y"] * scale + pad_h
        scaled.append({"x": x, "y": y})
    return scaled

def polygon_to_mask(points, target_size):
    """Convert polygon points to binary mask"""
    mask = np.zeros(target_size[::-1], dtype = np.uint8)  # target_size[::-1] = height, width
    pts = np.array([[p["x"], p["y"]] for p in points], np.int32)
    pts = pts.reshape((-1, 1, 2)) #-1: automatically infer dimension needed, 2: num. of dimension (xy = 2)
    cv2.fillPoly(mask, [pts], color = 1)
    return mask

"""### 2.4.1 Process Images and Masks

Process images and masks

For each image in the jpeg files, we'll extract the filename and generate a unique ID for the image (like 99_1), open the image and records its original size, resize the image for the CNN with padding to the target dimensions. The resized image is stored in a list along with its unique image ID (img_id).

Then generate binary masks for nodules (if available). Check if there are SVG polygons for this image in svg_polygons. Each polygon outlines a nodule in the original image. The polygon points are scaled to match the resized image using our custom scaling function. A binary mask is created from each polygon, where pixels inside the nodule = 1 (white) and outside = 0 (black). If there are multiple polygons in one image, they are combined into a single mask. The final mask is stored in masks_dict using the image ID as the key.

So we'll have a list of the resized image with it's unique image id and a dictionary of the resized image's binary map with it's unique image id.
"""

processed_images = []  # store (filename, PIL.Image)
masks_dict = {}        # key = "{case_number}_{image_index}", value = mask

for img_path in jpeg_files:
    filename = os.path.basename(img_path)
    img_id = os.path.splitext(filename)[0]  # [0] bc filename 99_1.jpg splittext gives (root, ext)
    img = Image.open(img_path)
    orig_size = img.size  # (width, height)

    # Resize with padding
    img_resized = ImageOps.pad(img, TARGET_SIZE, color = (0,0,0))
    processed_images.append((img_id, img_resized))

    # Generate masks if SVG polygons exist

    if img_id in svg_polygons:
        masks = []
        for polygon_dict in svg_polygons[img_id]:
            points = polygon_dict["points"]  # get the points for this polygon
            scaled_pts = scale_points(points, orig_size, TARGET_SIZE)
            mask = polygon_to_mask(scaled_pts, TARGET_SIZE)
            masks.append(mask)
        if masks:
            final_mask = np.clip(np.sum(masks, axis=0), 0, 1)  # combine multiple masks
            masks_dict[img_id] = final_mask

# Example visualization
plt.figure(figsize = (12, 5))

plt.subplot(1,3,1)
plt.imshow(img_resized, cmap = 'gray')
plt.title("Resized Image")

plt.subplot(1,3,2)
plt.imshow(mask, cmap = 'gray')
plt.title("Binary Mask")

plt.subplot(1,3,3)
plt.imshow(img_resized, cmap = 'gray')
plt.imshow(mask, cmap = 'Reds', alpha = 0.4)
plt.title("Overlay")
plt.show()

# Check 5 random examples
examples = random.sample(processed_images, 5)

for img_id, img in examples:
    mask = masks_dict.get(img_id)

    plt.figure(figsize = (20, 8))

    # resized image
    plt.subplot(1,3,1)
    plt.imshow(img, cmap = 'gray')
    plt.title(f"Image {img_id}")

    # mask
    plt.subplot(1,3,2)
    if mask is not None:
        plt.imshow(mask, cmap = 'gray')
    plt.title("Mask")

    # overlay
    plt.subplot(1,3,3)
    plt.imshow(img, cmap = 'gray')
    if mask is not None:
        plt.imshow(mask, cmap = 'Reds', alpha = 0.4)
    plt.title("Overlay")

    plt.show()

"""#3.0 Prepare the Data for Modeling

Next, we need to align images with their metadata and labels, but the images are named with their case number and their image number and the metadata just has their case number. So we need to merge. these two with a primary key with something like their case number.

First, we'll create a new dataframe containing all our processed images, with columns image_id and their case number. We'll merge this new dataframe with the metadata and perform a left merge on the number column where the left dataframe is the new dataframe and the right dataframe is the metadata table.
"""

# new image dataframe
image_df = pd.DataFrame({
    "image_id": [img_id for img_id, _ in processed_images]
    })
image_df["Number"] = image_df["image_id"].str.split("_").str[0].astype(int)

# left merge
metadata_df_expanded = image_df.merge(metadata_df_clean, on = "Number", how = "left")

# Check metadata
print('---Metadata Columns---\n')
print(metadata_df_expanded.columns)
print('\n ---Metadata Sample of Image Id and TIRADS--- \n')
print(metadata_df_expanded[['image_id', 'Tirads']].head())
print('\n ---Metadata Column Count--- \n')\
# count number of columns or features in metadata
print(metadata_df_expanded.shape[1])

# Check one processed image
print('\n---One Processed Image---\n')
print(processed_images[0][0])  # should match an image_id in metadata_df

# Check one mask
print('\n---One Mask Dimension---\n')
first_key = list(masks_dict.keys())[0]
print(first_key, masks_dict[first_key].shape)

metadata_df_expanded['Tirads'].value_counts()

"""Because there's an imbalance in scores, if we trained with this data, the model will probably learn to predict TI-RADS score 1 most of the time because that's the dominant class and will thus have poorer recall on higher TI-RADS scores where classification significantly matters more. As a result of this class imbalance, we will use class weights to make it more balanced. We will apply the weights after we split the data into training and testing sets.

Next, we need to prepare the data for our multimodal CNN architecture. We'll create a function to handle this by taking the aligned images, masks, and metadata and convert them into arrays that the model can use. It will resize and normalize images, ensures the masks are shaped correctly, converts the metadata into numerical features dropping identifiers and target labels and maps the TI-RADS scores into numerical labels. These arrays will align so each row of each array coreresponds to the same example. The function will return an images, masks, metadata and labels array which will be fed into the model for training.
"""

# create a fct to prepare dataset with resized images, masks, metadata to ensure they all match

def prepare_dataset(processed_images, masks_dict, metadata_expanded, invalid_images = set(), target_size = (224,224)):
    """
    Prepare arrays for multimodal CNN: images, masks, metadata, and labels.

    Arguments:
    - processed_images: list of tuples (img_id, PIL.Image)
    - masks_dict: dict {img_id: mask_array}
    - metadata_df: pandas DataFrame with encoded metadata and 'image_id' column
    - invalid_images: set of img_ids to exclude
    - target_size: desired image/mask size (width, height)

    Returns:
    - X_img, X_mask, X_meta, y arrays
    """

    # Filter out invalid images
    valid_images = [(img_id, img) for img_id, img in processed_images if img_id not in invalid_images]
    valid_masks_dict = {img_id: mask for img_id, mask in masks_dict.items() if img_id not in invalid_images}
    valid_metadata = metadata_expanded[~metadata_expanded['image_id'].isin(invalid_images)].reset_index(drop = True)

    # Create image array
    images_array = np.array([np.array(img.resize(target_size)) for img_id, img in valid_images], dtype = np.float32) / 255.0

    # Create mask array
    masks_list = []
    for img_id, _ in valid_images:
        mask = valid_masks_dict.get(img_id, np.zeros(target_size, dtype = np.uint8))
        masks_list.append(mask)
    masks_array = np.expand_dims(np.array(masks_list), axis = -1)

    # Create metadata array
    metadata_array = valid_metadata.drop(columns = ['image_id', 'Tirads']).to_numpy().astype(np.float32)

    # Create label array
    tirads_map = {'1':0, '2':1, '3':2, '4a':3, '4b':4, '4c':5, '5':6}
    labels_array = valid_metadata['Tirads'].map(tirads_map).to_numpy()

    return images_array, masks_array, metadata_array, labels_array

# Prepare dataset
X_img, X_mask, X_meta, y = prepare_dataset(processed_images, masks_dict, metadata_df_expanded, invalid_images, target_size = (224, 224))

print("---X_img Shape---\n", X_img.shape)
print("\n---X_mask Shape---\n", X_mask.shape)
print("\n---X_meta Shape---\n", X_meta.shape)
print("\n---y Shape---\n",  y.shape)

# Train test split
X_img_train, X_img_test, X_mask_train, X_mask_test, X_meta_train, X_meta_test, y_train, y_test = train_test_split(
    X_img, X_mask, X_meta, y, test_size = 0.2, stratify = y, shuffle = True, random_state = 42)

print("Train shapes:", X_img_train.shape, X_mask_train.shape, X_meta_train.shape, y_train.shape)
print("Test shapes:", X_img_test.shape, X_mask_test.shape, X_meta_test.shape, y_test.shape)

# Compute class weights from the training labels only
classes = np.unique(y_train)
class_weights = compute_class_weight(
    class_weight = 'balanced',
    classes = classes,
    y = y_train
)
class_weights = dict(zip(classes, class_weights))
print(class_weights)

"""# 4.0 CNN Model Architecture

we're going to build a function to easily instantiate the model with different parameters.

The function will take the following parameters:
ultrasound images shape, mask shape, metadata dimensions, and number of categories to predict.

The images and masks will go through a basic cnn architecture first with a convulational layer with 32 filters and kernel size  in the first layer where features are extracted from the images, a maxpooling layer to reduce spatial dimension while keeping important features, a second convulational layer with 64 filters, and finally a global average pooling layer where features are flattened to connect layers and summarize the image.

The metadata will undergo a neural network with two layers, the first having 32 neurons and the second having 16.

The images, masks, and metadata will all be combined together into a neural network for our first model.

The model will then be compiled setting up the optimizer, the loss function to measure errors, and performance metrics.

Finally the model will be fitted with the training data.

## 4.1 Build the CNN Model Architecture
"""

def build_multimodal_model(img_shape = (224, 224, 3), mask_shape = (224, 224, 1), meta_dim = 20, num_classes = 7):
    # Image branch
    img_input = Input(shape = img_shape, name = "image_input")
    x = layers.Conv2D(32, 3, activation = 'relu', padding = 'same')(img_input)
    x = layers.MaxPooling2D(2)(x)
    x = layers.Conv2D(64, 3, activation = 'relu', padding = 'same')(x)
    x = layers.GlobalAveragePooling2D()(x)

    # Mask branch
    mask_input = Input(shape = mask_shape, name = "mask_input")
    m = layers.Conv2D(16, 3, activation = 'relu', padding = 'same')(mask_input)
    m = layers.MaxPooling2D(2)(m)
    m = layers.Conv2D(32, 3, activation = 'relu', padding = 'same')(m)
    m = layers.GlobalAveragePooling2D()(m)

    # Metadata branch
    meta_input = Input(shape = (meta_dim,), name = "meta_input")
    d = layers.Dense(32, activation = 'relu')(meta_input)
    d = layers.Dense(16, activation = 'relu')(d)

    # Combine branches
    combined = layers.Concatenate()([x, m, d])
    z = layers.Dense(64, activation = 'relu')(combined)
    z = layers.Dense(32, activation = 'relu')(z)
    output = layers.Dense(num_classes, activation = 'softmax')(z)

    model = models.Model(inputs = [img_input, mask_input, meta_input], outputs=output)
    return model

# Build and compile the model
model = build_multimodal_model()
model.compile(optimizer = 'adam',
              loss = 'sparse_categorical_crossentropy',
              metrics = ['accuracy'])

# Print the model summary to inspect what the structure looks like
model.summary()

"""## 4.2 Fit the Model with Training Data"""

# Create a function for early stopping to monitor if model is improving
early_stop = EarlyStopping(
    monitor = 'val_loss',
    patience = 3,
    restore_best_weights = True
)

# Fit the model with training data
history = model.fit(
    [X_img_train, X_mask_train, X_meta_train],
    y_train,
    class_weight = class_weights,
    validation_split = 0.2,
    batch_size = 8,
    epochs = 30,
    callbacks = [early_stop],
    verbose = 1
)

# Last epoch values
print("Final training loss:", history.history['loss'][-1])
print("Final validation loss:", history.history['val_loss'][-1])
print("Final training accuracy:", history.history['accuracy'][-1])
print("Final validation accuracy:", history.history['val_accuracy'][-1])

# Best epoch with lowest validation loss (model will use those weights)
best_epoch_cnn = np.argmin(history.history['val_loss']) + 1 # since epoch 1 index 0
print(f"Best epoch (lowest val_loss): {best_epoch_cnn}")
print(f"Best val_loss: {min(history.history['val_loss']):.4f}")

"""This CNN model has a 62.46% training accuracy and a 60.53% validation accuracy.

## 4.3 Performance Metrics

### 4.3.1 CNN Training Loss and Accuracy
"""

# Training loss and accuracy history
train_loss = history.history['loss']
train_acc = history.history['accuracy']

# Validation loss and accuracy history
val_loss = history.history['val_loss']
val_acc = history.history['val_accuracy']

# Loss curve
plt.figure(figsize = (12, 5))
plt.subplot(1, 2, 1)
plt.plot(train_loss, label = 'Training Loss')
plt.plot(val_loss, label = 'Validation Loss')
plt.title('Model Loss over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

# Accuracy curve
plt.subplot(1, 2, 2)
plt.plot(train_acc, label = 'Training Accuracy')
plt.plot(val_acc, label = 'Validation Accuracy')
plt.title('Model Accuracy over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

plt.show()

"""### 4.3.2 CNN Test Classification Results"""

loss, acc = model.evaluate([X_img_test, X_mask_test, X_meta_test], y_test)

print(f"CNN Test Accuracy: {acc:.4f}")
print(f"CNN Test Loss: {loss:.4f}")

"""The CNN model had predicted 60% accuracy and a loss score of 1.03 on the test data."""

y_pred = model.predict([X_img_test, X_mask_test, X_meta_test])
y_pred_classes = y_pred.argmax(axis = 1)

print(classification_report(y_test, y_pred_classes))
print(confusion_matrix(y_test, y_pred_classes))

"""#6.0 Transfer Learning

Given our CNN model's performance, we'll try to improve it by using transfer learning. In this method, we will use a pretrained model that has alrealdy learned rich feature representations from massive datasets like ImageNet, in this case DenseNet121, and use it on the images, while at the same time use a simple CNN architecture for the masks, and a dense layer for the metadata. For the transfer learning base model, we'll freeze the weights so it won't be updated during training, allowing us to retain the pretrained visual features while training only the task-specific layers on our thyroid ultrasound dataset.

RadImageNet was considered as a base model for the transfer learning, however, obtaining the weights was not convenient as it's not easily available in tensorflow or keras. To use the weights, we need to source the pretrained RadImageNet weights, download the file locally to our computer, and then load it into the model.

## 6.1 Build the Transfer Learning Model Architecture
"""

def build_transfer_learning_model(
    img_shape = (224, 224, 3), mask_shape = (224, 224, 1), meta_dim = 20, num_classes = 7
):
  # Image branch removing the final classification layer (top = false) since we have different objectives and just want the extraction and no updating weights to base model
  img_input = Input(shape = img_shape, name = "image_input")
  base_model = DenseNet121(
      weights = "imagenet",
      include_top = False,
      input_tensor = img_input)
  base_model.trainable = False
  x = base_model.output
  x = layers.GlobalAveragePooling2D()(x)
  x = layers.Dense(128, activation = 'relu')(x)
  x = layers.Dropout(0.3)(x)

  # Mask branch
  mask_input = Input(shape = mask_shape, name = "mask_input")
  m = layers.Conv2D(32, (3, 3), activation = 'relu')(mask_input)
  m = layers.MaxPooling2D()(m)
  m = layers.Conv2D(64, (3, 3), activation = 'relu')(m)
  m = layers.GlobalAveragePooling2D()(m)
  m = layers.Dense(64, activation = 'relu')(m)

  # Metadat branch
  meta_input = Input(shape = (meta_dim,), name = "meta_input")
  d = layers.Dense(32, activation = 'relu')(meta_input)
  d = layers.Dropout(0.3)(d)
  d = layers.Dense(16, activation = 'relu')(d)

  # Combine
  combined = layers.concatenate([x, m, d])
  z = layers.Dense(64, activation = 'relu')(combined)
  z = layers.Dropout(0.3)(z)
  output = layers.Dense(num_classes, activation = 'softmax')(z)

  model = models.Model(inputs = [img_input, mask_input, meta_input], outputs = output)
  return model

# Build and compile the model
tl_model = build_transfer_learning_model()
tl_model.compile(optimizer = 'adam',
              loss = 'sparse_categorical_crossentropy',
              metrics = ['accuracy'])

# Print the model summary to inspect what the structure looks like
tl_model.summary()

"""## 6.2 Fit the Model with Training Data"""

# Fit the model with training data
tl_history = tl_model.fit(
    [X_img_train, X_mask_train, X_meta_train],
    y_train,
    class_weight = class_weights,
    validation_split = 0.2,
    batch_size = 8,
    epochs = 30,
    callbacks = [early_stop],
    verbose = 1
)

# Last epoch values
print("Final training loss:", tl_history.history['loss'][-1])
print("Final validation loss:", tl_history.history['val_loss'][-1])
print("Final training accuracy:", tl_history.history['accuracy'][-1])
print("Final validation accuracy:", tl_history.history['val_accuracy'][-1])

# Best epoch with lowest validation loss (model will use those weights)
best_epoch_tl = np.argmin(tl_history.history['val_loss']) + 1
print(f"Best epoch (lowest val_loss): {best_epoch_tl}")
print(f"Best val_loss: {min(tl_history.history['val_loss']):.4f}")

"""This transfer learning model has a 17.02% training accuracy and a 19.74% validation accuracy.

## 6.3 Performance Metrics

### 6.3.1 Transfer Learning Training Loss and Accuracy
"""

# Training loss and accuracy history
tl_train_loss = tl_history.history['loss']
tl_train_acc = tl_history.history['accuracy']

# Validation loss and accuracy history
tl_val_loss = tl_history.history['val_loss']
tl_val_acc = tl_history.history['val_accuracy']

# Loss curve
plt.figure(figsize = (12, 5))
plt.subplot(1, 2, 1)
plt.plot(tl_train_loss, label = 'Transfer Learning Training Loss')
plt.plot(tl_val_loss, label = 'Transfer Learning Validation Loss')
plt.title('Model Loss over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

# Accuracy curve
plt.subplot(1, 2, 2)
plt.plot(tl_train_acc, label = 'Transfer Learning Training Accuracy')
plt.plot(tl_val_acc, label = 'Transfer Learning Validation Accuracy')
plt.title('Model Accuracy over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

plt.show()

"""### 6.3.2 Transfer Learning Test Classification Results"""

tl_loss, tl_acc = tl_model.evaluate([X_img_test, X_mask_test, X_meta_test], y_test)

print(f"TL Test Accuracy: {tl_acc:.4f}")
print(f"TL Test Loss: {tl_loss:.4f}")

"""The transfer learning model had predicted 18.95% accuracy and a loss score of 1.95 on the test data."""

tl_y_pred = tl_model.predict([X_img_test, X_mask_test, X_meta_test])
tl_y_pred_classes = tl_y_pred.argmax(axis = 1)

print(classification_report(y_test, tl_y_pred_classes))
print(confusion_matrix(y_test, tl_y_pred_classes))

"""#7.0 Consolidating Labels

Our models performed poorly despite having balanced weights in classifying all labels, especially our transfer learning model. The problem might stem from the fact that TI-RADS scores are not distinct enough to dilineate from each other aside from the two polar opposites. Hence, in the next steps we will merge the lalbels so there are only three classes: benign, low-risk, and high-risk.

The benign class will combine TI-RADS scores 1 and 2. The low-risk class will consist of TI-RADS score 3. The high-risk class will combine TI-RADS scores 4 and 5.
"""

# Create a fct  to turn 1 & 2 to 0 (benign), 3 to 1 (low risk), and 4 & 5 to 2 (high risk)
def simplify_tirads(t):
    if t in [1, '1', 2, '2']:
        return 0
    elif t in [3, '3']:
        return 1
    elif t in ['4a', '4A', '4b', '4B', '4c', '4C', 5, '5']:
        return 2

metadata_df_expanded['tirads_simplified'] = metadata_df_expanded['Tirads'].apply(simplify_tirads)

metadata_df_expanded[['tirads_simplified', 'Tirads']].head(10)

"""## 7.1 Prepare Data with Newly Merged Labels"""

# create a fct to prepare dataset with resized images, masks, and metadata with merged labels
def prepare_dataset2(processed_images, masks_dict, metadata_expanded, invalid_images = set(), target_size = (224,224)):
    """
    Prepare arrays for multimodal CNN: images, masks, metadata, and labels.

    Arguments:
    - processed_images: list of tuples (img_id, PIL.Image)
    - masks_dict: dict {img_id: mask_array}
    - metadata_df: pandas DataFrame with encoded metadata and 'image_id' column
    - invalid_images: set of img_ids to exclude
    - target_size: desired image/mask size (width, height)

    Returns:
    - X_img, X_mask, X_meta, y arrays
    """

    # Filter out invalid images
    valid_images = [(img_id, img) for img_id, img in processed_images if img_id not in invalid_images]
    valid_masks_dict = {img_id: mask for img_id, mask in masks_dict.items() if img_id not in invalid_images}
    valid_metadata = metadata_expanded[~metadata_expanded['image_id'].isin(invalid_images)].reset_index(drop = True)

    # Create image array
    images_array = np.array([np.array(img.resize(target_size)) for img_id, img in valid_images], dtype = np.float32) / 255.0

    # Create mask array
    masks_list = []
    for img_id, _ in valid_images:
        mask = valid_masks_dict.get(img_id, np.zeros(target_size, dtype = np.uint8))
        masks_list.append(mask)
    masks_array = np.expand_dims(np.array(masks_list), axis = -1)

    # Create metadata array
    metadata_array = valid_metadata.drop(columns = ['image_id', 'Tirads', 'tirads_simplified']).to_numpy().astype(np.float32)

    # Create label array using the simplified TIRADS column
    labels_array = valid_metadata['tirads_simplified'].to_numpy()


    return images_array, masks_array, metadata_array, labels_array

# Prepare dataset
X_img2, X_mask2, X_meta2, y2 = prepare_dataset2(processed_images, masks_dict, metadata_df_expanded, invalid_images, target_size = (224, 224))

# Train test split
X_img_train2, X_img_test2, X_mask_train2, X_mask_test2, X_meta_train2, X_meta_test2, y_train2, y_test2 = train_test_split(
    X_img2, X_mask2, X_meta2, y2, test_size = 0.2, stratify = y2, shuffle = True, random_state = 42)

print("Train shapes:", X_img_train2.shape, X_mask_train2.shape, X_meta_train2.shape, y_train2.shape)
print("Test shapes:", X_img_test2.shape, X_mask_test2.shape, X_meta_test2.shape, y_test2.shape)

# Compute new class weights from the training labels only
classes2 = np.unique(y_train2)
class_weights2 = compute_class_weight(
    class_weight = 'balanced',
    classes = classes2,
    y = y_train2
)
class_weights2 = dict(zip(classes2, class_weights2))
print(class_weights2)

"""## 7.2 CNN Model with Consolidated Labels"""

# Fit the model with training data
history2 = model.fit(
    [X_img_train2, X_mask_train2, X_meta_train2],
    y_train2,
    class_weight = class_weights2,
    validation_split = 0.2,
    batch_size = 8,
    epochs = 30,
    callbacks = [early_stop],
    verbose = 1
)

# Last epoch values
print("Final training loss:", history2.history['loss'][-1])
print("Final validation loss:", history2.history['val_loss'][-1])
print("Final training accuracy:", history2.history['accuracy'][-1])
print("Final validation accuracy:", history2.history['val_accuracy'][-1])

# Best epoch with lowest validation loss (model will use those weights)
best_epoch_cnn2 = np.argmin(history2.history['val_loss']) + 1
print(f"Best epoch (lowest val_loss): {best_epoch_cnn2}")
print(f"Best val_loss: {min(history2.history['val_loss']):.4f}")

"""This CNN model has a 86.22% training accuracy and a 85.53% validation accuracy.

## 7.3 Transfer Learning Model with Consolidated Labels
"""

# Fit the model with training data
tl_history2 = tl_model.fit(
    [X_img_train2, X_mask_train2, X_meta_train2],
    y_train2,
    class_weight = class_weights2,
    validation_split = 0.2,
    batch_size = 8,
    epochs = 30,
    callbacks = [early_stop],
    verbose = 1
)

# Last epoch values
print("Final training loss:", tl_history2.history['loss'][-1])
print("Final validation loss:",tl_history2.history['val_loss'][-1])
print("Final training accuracy:", tl_history2.history['accuracy'][-1])
print("Final validation accuracy:", tl_history2.history['val_accuracy'][-1])

# Best epoch with lowest validation loss (model will use those weights)
best_epoch_tl2 = np.argmin(tl_history2.history['val_loss']) + 1
print(f"Best epoch (lowest val_loss): {best_epoch_tl2}")
print(f"Best val_loss: {min(tl_history2.history['val_loss']):.4f}")

"""This transfer learning model has a 18.63% training accuracy and a 3.95% validation accuracy which indicates it is overfitting and it is simply not learning.

## 7.4 Performance Metrics

### 7.4.1 CNN Model Performance Metrics

####7.4.1.1 Training Loss and Accuracy
"""

# Training loss and accuracy history
train_loss2 = history2.history['loss']
train_acc2 = history2.history['accuracy']

# Validation loss and accuracy history
val_loss2 = history2.history['val_loss']
val_acc2 = history2.history['val_accuracy']

# Loss curve
plt.figure(figsize = (12, 5))
plt.subplot(1, 2, 1)
plt.plot(train_loss2, label = 'Training Loss')
plt.plot(val_loss2, label = 'Validation Loss')
plt.title('Model Loss over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

# Accuracy curve
plt.subplot(1, 2, 2)
plt.plot(train_acc2, label = 'Training Accuracy')
plt.plot(val_acc2, label = 'Validation Accuracy')
plt.title('Model Accuracy over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

plt.show()

"""####7.4.1.2 Test Classification Results"""

loss2, acc2 = model.evaluate([X_img_test2, X_mask_test2, X_meta_test2], y_test2)

print(f"CNN Test Accuracy After Consolidation: {acc2:.4f}")
print(f"CNN Test Loss After Consolidation: {loss2:.4f}")

"""The CNN model had predicted 85.26% accuracy and a loss score of 0.36 on the test data."""

y_pred2 = model.predict([X_img_test2, X_mask_test2, X_meta_test2])
y_pred_classes2 = y_pred2.argmax(axis = 1)

print(classification_report(y_test2, y_pred_classes2))
print(confusion_matrix(y_test2, y_pred_classes2))

"""### 7.4.2 Transfer Learning Performance Metrics

####7.4.2.1 Training Loss and Accuracy
"""

# Training loss and accuracy history
tl_train_loss2 = tl_history2.history['loss']
tl_train_acc2 = tl_history2.history['accuracy']

# Validation loss and accuracy history
tl_val_loss2 = tl_history2.history['val_loss']
tl_val_acc2 = tl_history2.history['val_accuracy']

# Loss curve
plt.figure(figsize = (12, 5))
plt.subplot(1, 2, 1)
plt.plot(tl_train_loss2, label = 'Transfer Learning Training Loss')
plt.plot(tl_val_loss2, label = 'Transfer Learning Validation Loss')
plt.title('Model Loss over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

# Accuracy curve
plt.subplot(1, 2, 2)
plt.plot(tl_train_acc2, label = 'Transfer Learning Training Accuracy')
plt.plot(tl_val_acc2, label = 'Transfer Learning Validation Accuracy')
plt.title('Model Accuracy over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

plt.show()

"""####7.4.2.2 Test Classification Results"""

tl_loss2, tl_acc2 = tl_model.evaluate([X_img_test2, X_mask_test2, X_meta_test2], y_test2)

print(f"TL Test Accuracy After Consolidation: {tl_acc2:.4f}")
print(f"TL Test Loss After Consolidation: {tl_loss2:.4f}")

"""The transfer learning model had predicted 4.21% accuracy and a loss score of 1.20 on the test data."""

tl_y_pred2 = tl_model.predict([X_img_test2, X_mask_test2, X_meta_test2])
tl_y_pred_classes2 = tl_y_pred2.argmax(axis = 1)

print(classification_report(y_test2, tl_y_pred_classes2))
print(confusion_matrix(y_test2, tl_y_pred_classes2))

"""# 8.0 Conclusion

At first, when we ran the CNN model on all seven TI-RADS categories, it performed moderately well. The test accuracy was 60% and the macro F1-score was 0.57 indicating performance was uneven across classes. Looking at the confusion matrix, the model correctly classified common categories like TI-RADS 1 (24 out of 26) and TI-RADS 4c (9 out of 13), but it struggled with less frequent or visually similar categories such as TI-RADS 3 (2 out of 4), 4a (6 out of 19), and 4b (7 out of 16). This shows that the CNN could pick up clear features for some nodules, but mid-range scores were harder to distinguish most likely because they look similar on ultrasound.


In contrast, the transfer learning model using a pretrained EfficientNet architecture did not perform as well. Its test accuracy was 19% and the macro F1-score was only 0.05. From the confusion matrix, it mostly predicted TI-RADS 4a (18 out of 19 correct), and failed to generalize to other categories. This suggests that the features learned from natural images didn’t transfer well to thyroid ultrasounds and was probably hampered by the base model's frozen weights.


After consolidating the TI-RADS labels into three broader, clinically meaningful categories (benign, low-risk, and high-risk), the CNN’s performance improved substantially. Test accuracy went up to 85% and the macro F1-score to 0.67. Recall for each group was 0.71 for benign, 0.25 for low-risk, and 0.98 for high-risk, which matches the confusion matrix counts of 24/34, 1/4, and 56/57 correctly classified. The macro recall of 0.65 and F1-score of 0.67 show that performance is fairly balanced even with uneven class sizes, while the weighted F1-score of 0.85 confirms that overall, predictions align well with true labels.


The transfer learning model, on the other hand, performed worse than before consolidation, reaching 4% test accuracy and a macro F1-score of 0.03. It still struggled to identify benign and high-risk nodules, predicting mostly low-risk nodules (4 out of 4 correct) and missing all of the others; over-classifying nodules as low-risk. The macro recall of 0.33 and F1 of 0.03 show that it’s missing a lot of the subtlety in distinguishing between benign and high-risk nodules. This suggests that pretrained models like EfficientNet may not be ideal for specialized medical imaging, especially when their pretrained weights are frozen limiting their adaptability and the features learned from natural images do not transfer well to the subtle patterns in ultrasound scans.


Overall, simplifying the labels into clinically meaningful groups benefited the CNN model the most. It learned to focus on features that distinguish benign, low-risk, and high-risk nodules, which makes it more reliable for identifying the cases that matter most. In a medical context where missing a suspicious case is more costly than a false alarm, the CNN’s recall-driven improvement after consolidation is a promising result. However, the transfer learning architecture can be better improved by using pretrained weights from RadImageNet which is trained on 1.35 million radiological images. We decided against using RadImageNet because the download file for the weights was pretty large and cannot be called on in python and has to be sourced on a local machine or in the cloud.
"""